// Bundles the vendored pilo aria-tree (vendor/pilo-ariaTree) into a single IIFE string
// that browser.ts injects with Runtime.evaluate (no new Function — CSP-safe).
import { build } from "esbuild";
import { writeFileSync } from "node:fs";

const out = await build({
  entryPoints: ["vendor/pilo-ariaTree/index.ts"],
  bundle: true,
  format: "iife",
  globalName: "__askAriaTree",
  platform: "browser",
  target: "es2020",
  minify: true,
  write: false,
  legalComments: "inline",
});
const code = out.outputFiles[0].text;
writeFileSync(
  "src/lib/ariaTree.generated.ts",
  `// GENERATED by scripts/build-aria.mjs from vendor/pilo-ariaTree (mozilla/pilo, Apache-2.0;\n` +
    `// derived from Microsoft Playwright, Apache-2.0). Do not edit by hand.\n` +
    `export const ARIA_TREE_SCRIPT = ${JSON.stringify(code)};\n`,
);
console.log(`ariaTree bundle: ${code.length} bytes`);
